// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"job-exec/internal/app/server/dao/internal"
)

// internalTaskMetaDao is internal type for wrapping internal DAO implements.
type internalTaskMetaDao = *internal.TaskMetaDao

// taskMetaDao is the data access object for table task_meta.
// You can define custom methods on it to extend its functionality as you wish.
type taskMetaDao struct {
	internalTaskMetaDao
}

var (
	// TaskMeta is globally public accessible object for table task_meta operations.
	TaskMeta = taskMetaDao{
		internal.NewTaskMetaDao(),
	}
)

// Fill with you ideas below.
