// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: task_report.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*TaskResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	AgentIp string        `protobuf:"bytes,2,opt,name=AgentIp,proto3" json:"AgentIp,omitempty"`
}

func (x *TaskReportReq) Reset() {
	*x = TaskReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportReq) ProtoMessage() {}

func (x *TaskReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_task_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportReq.ProtoReflect.Descriptor instead.
func (*TaskReportReq) Descriptor() ([]byte, []int) {
	return file_task_report_proto_rawDescGZIP(), []int{0}
}

func (x *TaskReportReq) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *TaskReportReq) GetAgentIp() string {
	if x != nil {
		return x.AgentIp
	}
	return ""
}

type TaskReportRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignTasks []*TaskMetaFix `protobuf:"bytes,1,rep,name=AssignTasks,proto3" json:"AssignTasks,omitempty"`
}

func (x *TaskReportRes) Reset() {
	*x = TaskReportRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskReportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportRes) ProtoMessage() {}

func (x *TaskReportRes) ProtoReflect() protoreflect.Message {
	mi := &file_task_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportRes.ProtoReflect.Descriptor instead.
func (*TaskReportRes) Descriptor() ([]byte, []int) {
	return file_task_report_proto_rawDescGZIP(), []int{1}
}

func (x *TaskReportRes) GetAssignTasks() []*TaskMetaFix {
	if x != nil {
		return x.AssignTasks
	}
	return nil
}

var File_task_report_proto protoreflect.FileDescriptor

var file_task_report_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x13, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x66, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x53, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x28, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x70, 0x22, 0x42, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x78, 0x52, 0x0b, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x32, 0x3d, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x61, 0x73, 0x6b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_report_proto_rawDescOnce sync.Once
	file_task_report_proto_rawDescData = file_task_report_proto_rawDesc
)

func file_task_report_proto_rawDescGZIP() []byte {
	file_task_report_proto_rawDescOnce.Do(func() {
		file_task_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_report_proto_rawDescData)
	})
	return file_task_report_proto_rawDescData
}

var file_task_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_report_proto_goTypes = []interface{}{
	(*TaskReportReq)(nil), // 0: v1.TaskReportReq
	(*TaskReportRes)(nil), // 1: v1.TaskReportRes
	(*TaskResult)(nil),    // 2: v1.TaskResult
	(*TaskMetaFix)(nil),   // 3: v1.TaskMetaFix
}
var file_task_report_proto_depIdxs = []int32{
	2, // 0: v1.TaskReportReq.Results:type_name -> v1.TaskResult
	3, // 1: v1.TaskReportRes.AssignTasks:type_name -> v1.TaskMetaFix
	0, // 2: v1.Service.TaskReport:input_type -> v1.TaskReportReq
	1, // 3: v1.Service.TaskReport:output_type -> v1.TaskReportRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_report_proto_init() }
func file_task_report_proto_init() {
	if File_task_report_proto != nil {
		return
	}
	file_task_meta_fix_proto_init()
	file_task_result_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_task_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_report_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskReportRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_report_proto_goTypes,
		DependencyIndexes: file_task_report_proto_depIdxs,
		MessageInfos:      file_task_report_proto_msgTypes,
	}.Build()
	File_task_report_proto = out.File
	file_task_report_proto_rawDesc = nil
	file_task_report_proto_goTypes = nil
	file_task_report_proto_depIdxs = nil
}
