// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: task_meta_fix.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskMetaFix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"任务id"`                  // 任务id
	Title      string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty" dc:"标题"`               // 标题
	Account    string                 `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty" dc:"脚本执行账号"`       // 脚本执行账号
	ExecHosts  []string               `protobuf:"bytes,4,rep,name=ExecHosts,proto3" json:"ExecHosts,omitempty" dc:"执行的机器列表"`  // 执行的机器列表
	Script     string                 `protobuf:"bytes,5,opt,name=Script,proto3" json:"Script,omitempty" dc:"执行的脚本"`          // 执行的脚本
	ScriptArgs string                 `protobuf:"bytes,6,opt,name=ScriptArgs,proto3" json:"ScriptArgs,omitempty" dc:"脚本参数"`   // 脚本参数
	Creator    []string               `protobuf:"bytes,7,rep,name=Creator,proto3" json:"Creator,omitempty" dc:"创建者"`          // 创建者
	Done       int32                  `protobuf:"varint,8,opt,name=Done,proto3" json:"Done,omitempty" dc:"执行是否结束：0:没结束 1:结束"` // 执行是否结束：0:没结束 1:结束
	CreateAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`                 //
	UpdateAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`                //
	DeleteAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=DeleteAt,proto3" json:"DeleteAt,omitempty"`                //
}

func (x *TaskMetaFix) Reset() {
	*x = TaskMetaFix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_meta_fix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskMetaFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetaFix) ProtoMessage() {}

func (x *TaskMetaFix) ProtoReflect() protoreflect.Message {
	mi := &file_task_meta_fix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetaFix.ProtoReflect.Descriptor instead.
func (*TaskMetaFix) Descriptor() ([]byte, []int) {
	return file_task_meta_fix_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMetaFix) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskMetaFix) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskMetaFix) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *TaskMetaFix) GetExecHosts() []string {
	if x != nil {
		return x.ExecHosts
	}
	return nil
}

func (x *TaskMetaFix) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *TaskMetaFix) GetScriptArgs() string {
	if x != nil {
		return x.ScriptArgs
	}
	return ""
}

func (x *TaskMetaFix) GetCreator() []string {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *TaskMetaFix) GetDone() int32 {
	if x != nil {
		return x.Done
	}
	return 0
}

func (x *TaskMetaFix) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *TaskMetaFix) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *TaskMetaFix) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

var File_task_meta_fix_proto protoreflect.FileDescriptor

var file_task_meta_fix_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf9, 0x02, 0x0a, 0x0b, 0x54,
	0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78,
	0x65, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x45,
	0x78, 0x65, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x72, 0x67, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f,
	0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x36,
	0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x36,
	0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_meta_fix_proto_rawDescOnce sync.Once
	file_task_meta_fix_proto_rawDescData = file_task_meta_fix_proto_rawDesc
)

func file_task_meta_fix_proto_rawDescGZIP() []byte {
	file_task_meta_fix_proto_rawDescOnce.Do(func() {
		file_task_meta_fix_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_meta_fix_proto_rawDescData)
	})
	return file_task_meta_fix_proto_rawDescData
}

var file_task_meta_fix_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_task_meta_fix_proto_goTypes = []interface{}{
	(*TaskMetaFix)(nil),           // 0: v1.TaskMetaFix
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_task_meta_fix_proto_depIdxs = []int32{
	1, // 0: v1.TaskMetaFix.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 1: v1.TaskMetaFix.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 2: v1.TaskMetaFix.DeleteAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_task_meta_fix_proto_init() }
func file_task_meta_fix_proto_init() {
	if File_task_meta_fix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_meta_fix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskMetaFix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_meta_fix_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_meta_fix_proto_goTypes,
		DependencyIndexes: file_task_meta_fix_proto_depIdxs,
		MessageInfos:      file_task_meta_fix_proto_msgTypes,
	}.Build()
	File_task_meta_fix_proto = out.File
	file_task_meta_fix_proto_rawDesc = nil
	file_task_meta_fix_proto_goTypes = nil
	file_task_meta_fix_proto_depIdxs = nil
}
